export const columns = {
  code: 0,
  data: {
    current: 1,
    orders: [],
    pages: 2,
    records: [
      {
        communityName: "汤巷社区",
        currentStateName: "",
        idCard: "02230223",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 3,
        managementMeasuresName: "居家监测14",
        name: "0223",
        sampleDate: "",
        sourceId: 7,
        sourceName: "中高风险地区人员（完成14天集中隔离）",
        streetName: "崇安寺街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
        children: [
          {
            communityName: "汤巷社区",
            currentStateName: "",
            idCard: "022302231",
            isTest: false,
            lingXiCollectTime: "",
            lingXiResult: "未采样",
            lingXiResultType: 1,
            lingXiTaskQueryTime: "2022-08-13 08:43:42",
            managementMeasuresId: 3,
            managementMeasuresName: "居家监测14",
            name: "0223",
            sampleDate: "",
            sourceId: 7,
            sourceName: "中高风险地区人员（完成14天集中隔离）",
            streetName: "崇安寺街道",
            testDate: "2022-08-13",
            testDesc: "未采样",
            children: [
              {
                communityName: "汤巷社区",
                currentStateName: "",
                idCard: "02230225",
                isTest: false,
                lingXiCollectTime: "",
                lingXiResult: "未采样",
                lingXiResultType: 1,
                lingXiTaskQueryTime: "2022-08-13 08:43:42",
                managementMeasuresId: 3,
                managementMeasuresName: "居家监测14",
                name: "0223",
                sampleDate: "",
                sourceId: 7,
                sourceName: "中高风险地区人员（完成14天集中隔离）",
                streetName: "崇安寺街道",
                testDate: "2022-08-13",
                testDesc: "未采样",
                children: [
                  {
                    communityName: "汤巷社区",
                    currentStateName: "",
                    idCard: "022302238",
                    isTest: false,
                    lingXiCollectTime: "",
                    lingXiResult: "未采样",
                    lingXiResultType: 1,
                    lingXiTaskQueryTime: "2022-08-13 08:43:42",
                    managementMeasuresId: 3,
                    managementMeasuresName: "居家监测14",
                    name: "0223",
                    sampleDate: "",
                    sourceId: 7,
                    sourceName: "中高风险地区人员（完成14天集中隔离）",
                    streetName: "崇安寺街道",
                    testDate: "2022-08-13",
                    testDesc: "未采样",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        communityName: "汤巷社区",
        currentStateName: "健康监测",
        idCard: "993",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 21,
        managementMeasuresName: "“3+4+7”健康管理",
        name: "dd",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "崇安寺街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
      {
        communityName: "后西溪社区",
        currentStateName: "严格居家健康监测",
        idCard: "995",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 27,
        managementMeasuresName: "三天严格居家",
        name: "ee",
        sampleDate: "",
        sourceId: 20,
        sourceName: "同住人员",
        streetName: "崇安寺街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
        children: [
          {
            communityName: "后西溪社区",
            currentStateName: "严格居家健康监测",
            idCard: "9951",
            isTest: false,
            lingXiCollectTime: "",
            lingXiResult: "未采样",
            lingXiResultType: 1,
            lingXiTaskQueryTime: "2022-08-13 08:43:42",
            managementMeasuresId: 27,
            managementMeasuresName: "三天严格居家",
            name: "ee",
            sampleDate: "",
            sourceId: 20,
            sourceName: "同住人员",
            streetName: "崇安寺街道",
            testDate: "2022-08-13",
            testDesc: "未采样",
            children: [
              {
                communityName: "后西溪社区",
                currentStateName: "严格居家健康监测",
                idCard: "9957",
                isTest: false,
                lingXiCollectTime: "",
                lingXiResult: "未采样",
                lingXiResultType: 1,
                lingXiTaskQueryTime: "2022-08-13 08:43:42",
                managementMeasuresId: 27,
                managementMeasuresName: "三天严格居家",
                name: "ee",
                sampleDate: "",
                sourceId: 20,
                sourceName: "同住人员",
                streetName: "崇安寺街道",
                testDate: "2022-08-13",
                testDesc: "未采样",
                children: [
                  {
                    communityName: "后西溪社区",
                    currentStateName: "严格居家健康监测",
                    idCard: "9958",
                    isTest: false,
                    lingXiCollectTime: "",
                    lingXiResult: "未采样",
                    lingXiResultType: 1,
                    lingXiTaskQueryTime: "2022-08-13 08:43:42",
                    managementMeasuresId: 27,
                    managementMeasuresName: "三天严格居家",
                    name: "ee",
                    sampleDate: "",
                    sourceId: 20,
                    sourceName: "同住人员",
                    streetName: "崇安寺街道",
                    testDate: "2022-08-13",
                    testDesc: "未采样",
                  },
                ],
              },
            ],
          },
          {
            communityName: "后西溪社区",
            currentStateName: "严格居家健康监测",
            idCard: "99579",
            isTest: false,
            lingXiCollectTime: "",
            lingXiResult: "未采样",
            lingXiResultType: 1,
            lingXiTaskQueryTime: "2022-08-13 08:43:42",
            managementMeasuresId: 27,
            managementMeasuresName: "三天严格居家",
            name: "ee",
            sampleDate: "",
            sourceId: 20,
            sourceName: "同住人员",
            streetName: "崇安寺街道",
            testDate: "2022-08-13",
            testDesc: "未采样",
            children: [
              {
                communityName: "后西溪社区",
                currentStateName: "严格居家健康监测",
                idCard: "99500",
                isTest: false,
                lingXiCollectTime: "",
                lingXiResult: "未采样",
                lingXiResultType: 1,
                lingXiTaskQueryTime: "2022-08-13 08:43:42",
                managementMeasuresId: 27,
                managementMeasuresName: "三天严格居家",
                name: "ee",
                sampleDate: "",
                sourceId: 20,
                sourceName: "同住人员",
                streetName: "崇安寺街道",
                testDate: "2022-08-13",
                testDesc: "未采样",
              },
            ],
          },
        ],
      },
      {
        communityName: "塔影二村社区",
        currentStateName: "健康监测",
        idCard: "996",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 10,
        managementMeasuresName: "健康监测",
        name: "ff",
        sampleDate: "",
        sourceId: 14,
        sourceName: "其他",
        streetName: "广益街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
        children: [
          {
            communityName: "塔影二村社区",
            currentStateName: "健康监测",
            idCard: "9916",
            isTest: false,
            lingXiCollectTime: "",
            lingXiResult: "未采样",
            lingXiResultType: 1,
            lingXiTaskQueryTime: "2022-08-13 08:43:42",
            managementMeasuresId: 10,
            managementMeasuresName: "健康监测",
            name: "ff",
            sampleDate: "",
            sourceId: 14,
            sourceName: "其他",
            streetName: "广益街道",
            testDate: "2022-08-13",
            testDesc: "未采样",
            children: [
              {
                communityName: "塔影二村社区",
                currentStateName: "健康监测",
                idCard: "99126",
                isTest: false,
                lingXiCollectTime: "",
                lingXiResult: "未采样",
                lingXiResultType: 1,
                lingXiTaskQueryTime: "2022-08-13 08:43:42",
                managementMeasuresId: 10,
                managementMeasuresName: "健康监测",
                name: "ff",
                sampleDate: "",
                sourceId: 14,
                sourceName: "其他",
                streetName: "广益街道",
                testDate: "2022-08-13",
                testDesc: "未采样",
              },
            ],
          },
        ],
      },
      {
        communityName: "广瑞一村社区",
        currentStateName: "健康监测",
        idCard: "997",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 20,
        managementMeasuresName: "“3+11”14天健康管理",
        name: "gg",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "广益街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
        children: [
          {
            communityName: "广瑞一村社区",
            currentStateName: "健康监测",
            idCard: "9979",
            isTest: false,
            lingXiCollectTime: "",
            lingXiResult: "未采样",
            lingXiResultType: 1,
            lingXiTaskQueryTime: "2022-08-13 08:43:42",
            managementMeasuresId: 20,
            managementMeasuresName: "“3+11”14天健康管理",
            name: "gg",
            sampleDate: "",
            sourceId: 16,
            sourceName: "低风险地区需健康监测人员",
            streetName: "广益街道",
            testDate: "2022-08-13",
            testDesc: "未采样",
          },
        ],
      },
      {
        communityName: "广瑞二村社区",
        currentStateName: "健康监测",
        idCard: "998",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 21,
        managementMeasuresName: "“3+4+7”健康管理",
        name: "hh",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "广益街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
      {
        communityName: "锡澄新村社区",
        currentStateName: "健康监测",
        idCard: "999",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 21,
        managementMeasuresName: "“3+4+7”健康管理",
        name: "ii",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "北大街街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
      {
        communityName: "汤巷社区",
        currentStateName: "健康监测",
        idCard: "1000",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 21,
        managementMeasuresName: "“3+4+7”健康管理",
        name: "jj",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "崇安寺街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
      {
        communityName: "锡山新村社区",
        currentStateName: "健康监测",
        idCard: "1001",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 21,
        managementMeasuresName: "“3+4+7”健康管理",
        name: "kk",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "惠山街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
      {
        communityName: "汤巷社区",
        currentStateName: "健康监测",
        idCard: "1006",
        isTest: false,
        lingXiCollectTime: "",
        lingXiResult: "未采样",
        lingXiResultType: 1,
        lingXiTaskQueryTime: "2022-08-13 08:43:42",
        managementMeasuresId: 20,
        managementMeasuresName: "“3+11”14天健康管理",
        name: "uu",
        sampleDate: "",
        sourceId: 16,
        sourceName: "低风险地区需健康监测人员",
        streetName: "崇安寺街道",
        testDate: "2022-08-13",
        testDesc: "未采样",
      },
    ],
    searchCount: true,
    size: 10,
    total: 13,
  },
  msg: "执行成功",
};
